<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ZTLW-31" failures="6" tests="20" name="Test" time="26.07" errors="0" timestamp="2023-05-09T11:08:16 IST">
  <testcase classname="api.testCases.DDTests" name="testPostuser" time="2.127"/>
  <testcase classname="api.testCases.DDTests" name="testPostuser" time="1.069"/>
  <testcase classname="api.testCases.DDTests" name="testPostuser" time="1.042"/>
  <testcase classname="api.testCases.DDTests" name="testPostuser" time="1.05"/>
  <testcase classname="api.testCases.DDTests" name="testGetUser" time="1.084"/>
  <testcase classname="api.testCases.DDTests" name="testGetUser" time="1.067"/>
  <testcase classname="api.testCases.DDTests" name="testGetUser" time="1.076"/>
  <testcase classname="api.testCases.DDTests" name="testGetUser" time="1.091"/>
  <testcase classname="api.testCases.DDTests" name="testDeleteUser" time="1.036">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.testCases.DDTests.testDeleteUser(DDTests.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
  <testcase classname="api.testCases.DDTests" name="testDeleteUser" time="1.06">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.testCases.DDTests.testDeleteUser(DDTests.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
  <testcase classname="api.testCases.DDTests" name="testDeleteUser" time="1.081">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.testCases.DDTests.testDeleteUser(DDTests.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
  <testcase classname="api.testCases.DDTests" name="testDeleteUser" time="1.062">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.testCases.DDTests.testDeleteUser(DDTests.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
  <testcase classname="api.testCases.UserTests" name="testPostUser" time="1.129"/>
  <testcase classname="api.testCases.UserTests" name="testGetUser" time="1.015"/>
  <testcase classname="api.testCases.UserTests" name="testUpdateUser" time="2.112"/>
  <testcase classname="api.testCases.UserTests" name="testDeleteUser" time="1.043">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.testCases.UserTests.testDeleteUser(UserTests.java:74)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
  <testcase classname="api.testCases.UserTests2" name="testPostUser" time="1.017"/>
  <testcase classname="api.testCases.UserTests2" name="testGetUser" time="1.042"/>
  <testcase classname="api.testCases.UserTests2" name="testUpdateUser" time="2.174"/>
  <testcase classname="api.testCases.UserTests2" name="testDeleteUser" time="1.05">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.testCases.UserTests2.testDeleteUser(UserTests2.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
</testsuite> <!-- Test -->
